apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wwsq5cwnq-python 
  janus-idp.io/tekton: wwsq5cwnq-python
  backstage.io/kubernetes-id: wwsq5cwnq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wwsq5cwnq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  