apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wwsq5cwnq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wwsq5cwnq-python 
  name: wwsq5cwnq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wwsq5cwnq-python 
